version: '2'
services:
  redis:
    image: redis:7.0.5
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/redis/data:/data"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

  mongodb:
    image: mongo:5.0.8
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/mongodb/db:/data/db"
    restart: always
    ports:
      - "27017:27017"
    command: mongod

  mysqldb:
    image: mysql:5.7.34
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/mysqldb/lib/mysql:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_MONGODB_SERVER=
    restart: always
    ports:
      - "8081:8081"
    command: mongo-express

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=1234
    restart: always
    ports:
      - "8082:80"

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:0.8.1
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8083:8081"
