version: '2.4'
services:
  mongo-express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_MONGODB_SERVER=
    restart: always
    ports:
      - "8081:8081"
    command: mongo-express

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=1234
    restart: always
    ports:
      - "8082:80"

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:0.8.1
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8083:8081"
