version: '2.4'
services:
  redis:
    image: redis:7.0.5
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/redis/data:/data"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

  mongodb:
    image: mongo:5.0.8
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/mongodb/db:/data/db"
    restart: always
    ports:
      - "27017:27017"
    command: mongod

  mysqldb:
    image: mysql:5.7.34
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/dbs/mysqldb/lib/mysql:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

  rabbitmq:
    image: rabbitmq:3.13.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - "/var/store/dbs/rabbitmq:/var/lib/rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672
    mem_limit: 1g
    memswap_limit: 2g

  ydb:
    image: ydbplatform/local-ydb:25.2.1
    ## container_name: ydb-local
    ## hostname: ydb
    restart: always
    environment:
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_KAFKA_PROXY_PORT=9092
    volumes:
      - "/var/store/dbs/ydb/certs:/ydb_certs"
      - "/var/store/dbs/ydb/data:/ydb_data"
    ports:
      - "2135:2135" # gRPC over TLS (grpcs)
      - "2136:2136" # gRPC without TLS
      - "8765:8765" # HTTP UI/monitoring
      - "5432:5432" # PostgreSQL-compatible endpoint
      - "9092:9092" # Kafka-compatible endpoint
    command: []
